### ISSUE TITLE
Jet telegram reports wrong changes in fees

### ISSUE THREAD

**Issue by Deekee62** [itsneski/lightning-jet#20]
I've changes the local fees from 199 to 299 but jet telegram reported

<img width="816" alt="image" src="https://user-images.githubusercontent.com/33904339/141055677-cc43e902-44e2-421e-9759-8d72904c1fd1.png">

But Thunderhub shows the following

<img width="742" alt="image" src="https://user-images.githubusercontent.com/33904339/141056052-e77f2177-a622-476f-9450-0fff878a1357.png">

**Comment by pleb21** [comment]
I think there are two things here;

1. Telegram notification comes when peer changes their fee(me thinks!) so this notification should not have come when you changed the fee, in the first case 
2. although, the telegram notification shows the `from` and `to` fields incorrectly (for eg, in the case above, it should have been from 209 to 160;)

**Comment by Deekee62** [comment]
The fees of the peer haven't changed at all

**Comment by pleb21** [comment]
oh, those were just my guesses. point 2 still stands in my case though.

**Comment by itsneski** [comment]
"Telegram notification comes when peer changes their fee(me thinks!) so this notification should not have come when you changed the fee, in the first place." - correct, the notification comes when the peer changes fees on their end, it does not notify when the node operator changes the fees locally.
"although, the telegram notification shows the from and to fields incorrectly (for eg, in the case above, it should have been from 209 to 160; perhaps because the peer changed the fee to 160)" - this will be fixed in the next git push.
