### ISSUE TITLE
jet restart all, telegram started before stopping

### ISSUE THREAD

**Issue by Deekee62** [itsneski/lightning-jet#28]
I think there might be an error when restarting all services after I pulled the changes.

It seems that telegram is stared and then stopped instead of vice versa!

<img width="192" alt="image" src="https://user-images.githubusercontent.com/33904339/143684356-d1c2ce6d-8539-4fb9-be76-dff713f0fc89.png">

**Comment by Deekee62** [comment]
I just upgraded my node and therefore had to` jet start daddy` and here again the bot said that telegram has stopped!

<img width="822" alt="image" src="https://user-images.githubusercontent.com/33904339/143689132-ddef501a-9ed1-40c7-a1fe-98278489885b.png">

...but if I check using `jet status` telegram seems to be running just fine :-)

<img width="462" alt="image" src="https://user-images.githubusercontent.com/33904339/143689167-e1b802a5-f0d7-43cc-83b2-3ad0e2db3b4b.png">

**Comment by itsneski** [comment]
"It seems that telegram is stared and then stopped instead of vice versa!" - start & stop happen in the right sequence, but the telegram notifications get mixed up sometimes. I think this is due to messages being sent in async, so that there is no guarantee that the telegram will receive it in the [right] order.

"I just upgraded my node and therefore had to jet start daddy and here again the bot said that telegram has stopped!" - when the telegram service is stopped (e.g. by jet restart all), it stops sending the heartbeat. The heartbeat for the message poll (from db) is 30sec.  When daddy is back online and the heartbeat was not seen for 1min (2x30sec), it'll restart the telegram service. Extra restart is not an issue as long as there is no bug in the algo (e.g. it begins to restart too often).

**Comment by itsneski** [comment]
Fixed in the latest git push:
- git pull
- jet restart telegram
