### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by obvioussummer46** [itsneski/lightning-jet#40]
When jet tries to rebalance and fails due to high fee, it sees the min fee that would be required to rebalance. So would be great if it could save this data and provide it as a recomendation per peer,  like rebalance will likely to go through with X ppm

**Comment by itsneski** [comment]
Good idea. Jet can store the min of prospective rebalances it encounters and factor it into fee analysis.

**Comment by itsneski** [comment]
two new columns will be added to jet rebalance-history, ppm and min, with 'ppm' being actual ppm used during rebalance and 'min' being the min ppm needed to rebalance in case of a failure due to higher fee.
<img width="1067" alt="Screen Shot 2021-12-26 at 9 09 06 PM" src="https://user-images.githubusercontent.com/91937527/147438141-565ba64e-38fc-49ac-8f99-e91989165a7c.png">
