### ISSUE TITLE
Logger restart, [Error: SQLITE_BUSY: database is locked

### ISSUE THREAD

**Issue by Deekee62** [itsneski/lightning-jet#57]
Today the htlc-logger started out of the blue!

<img width="165" alt="image" src="https://user-images.githubusercontent.com/33904339/150737370-fb2509da-121b-429e-8394-5849fe9a54de.png">

The following entry could be found in htlc-logger.log:

```
01/24 07:48:05 AM
logging event: {
  incoming_channel_id: '785606555749908480',
  outgoing_channel_id: '767492101637013505',
  incoming_htlc_id: '83618',
  outgoing_htlc_id: '0',
  timestamp_ns: '1643006885240308298',
  event_type: 'FORWARD',
  link_fail_event: {
    info: {
      incoming_timelock: 720411,
      outgoing_timelock: 720371,
      incoming_amt_msat: '436281795',
      outgoing_amt_msat: '436151386'
    },
    wire_failure: 'TEMPORARY_CHANNEL_FAILURE',
    failure_detail: 'INSUFFICIENT_BALANCE',
    failure_string: 'insufficient bandwidth to route htlc'
  },
  event: 'link_fail_event'
}
node:events:368
      throw er; // Unhandled 'error' event
      ^

[Error: SQLITE_BUSY: database is locked
Emitted 'error' event on Statement instance at:
] {
  errno: 5,
  code: 'SQLITE_BUSY'
}

---------------------------------------
01/24 07:50:22 AM
subscribing to htlc events
```

Many thanks in advance for applying a fix :-)

**Comment by itsneski** [comment]
The logger service auto-restarted due to an uncaught exception. The exception was generated due to a rarely observed db error, caused by two simultaneous [atomic] writes needing access to the db. The fix is to put try & catch clause around the db call, so that the logger does not restart. Ideally, the long term fix is to root cause the db exception.

The issue isn't critical, as the daddy/watchdog service auto-restarted the logger service.

**Comment by Deekee62** [comment]
Just catched another one today...
